name: flutter_getx_starter_template
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  #for dynamic ui
  flutter_screenutil: ^5.3.1

  #for state management
  get: ^4.6.1
  get_storage: ^2.0.3

  image_picker: ^1.0.1
  image_cropper: ^3.0.2

  #for date formatting
  intl: ^0.18.0

  octo_image: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # flutter pub run change_app_package_name:main com.new.package.name
  change_app_package_name: ^1.1.0
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/